### ISSUE TITLE
Check if we can store the Verdaccio state in `.nx` folder

### ISSUE THREAD

**Issue by BioPhoton** [push-based/nx-verdaccio#34]
Currently if we start verdaccio we store the file in the environment folder.
Research if it makes sense to store that file under `.nx`.

**Comment by BioPhoton** [comment]
Imho it is a good idea to keep the file inside the environment

**Comment by getlarge** [comment]
It would be nice not to add yet another dot folder in the repositories. But maybe there is a risk that Nx will wipe the file?

**Comment by BioPhoton** [comment]
The file does not exist in a dot folder but inside the environment folder. Also the file only is there if the server is running. Stopping the server will remove the file too. So the cached output does not contain this file.
