### ISSUE TITLE
refactor: use `runExecutor` from `@nx/devkit` instead of importing the executor implementation

### ISSUE THREAD

**Issue by getlarge** [push-based/nx-verdaccio#6]
There might be a small performance penalty, but it will ensure that options for a given configuration are loaded (it might be very useful in the future of this tool!) and validated.

**Comment by BioPhoton** [comment]
@getlarge Thanks for the input. I'm fine with the small perf panalty. 
Could you be so kind and point out where we should use it? Like file and line pls 🙏

**Comment by getlarge** [comment]
I can do it. Just wanted to be sure you are with that.

**Comment by BioPhoton** [comment]
It seems in this repo there is not a lot of discussion need :)

**Comment by BioPhoton** [comment]
Started implemented it and love it!!
